language: php

matrix:
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
      env: DEPLOY=true
    - hhvm
  fast_finish: true
  allow_failures:
    - php: hhvm

script:
  - vendor/bin/tester tests -s
  - php $(composer global config bin-dir --absolute)/code-checker -d app
  - composer run-script lint
  - composer run-script cs
  - composer run-script phpstan

before_script:
  - phpenv config-rm xdebug.ini
  # Install Nette Tester & Code Checker
  - mv app/config/config.local.neon.default app/config/config.local.neon
  - composer install --no-interaction --dev --prefer-source
  - composer global require nette/code-checker ^3.0 --no-interaction --prefer-source


before_deploy:
  - source utils/package.sh

deploy:
  - provider: bintray
    file: utils/bintray.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      condition: $DEPLOY = true
