language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

script:
  - vendor/bin/tester tests -s
  - php code-checker/src/code-checker.php -d app

before_script:
  # Install Nette Tester & Code Checker
  - mv app/config/config.local.neon.default app/config/config.local.neon
  - composer install --no-interaction --dev --prefer-source
  - composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source
